### ISSUE TITLE
Danske get_bank_certificate `decrypt_embedded_key': undefined method content

### ISSUE THREAD

**Issue by tontsa** [devlab-oy/sepa#64]
Hi,

Trying to get Danske's encryption/bank_signing/bank_root certs using following code:
#!/usr/local/bin/ruby

require "base64"
require "sepafm"

params = {
  bank: :danske,
  target_id: 'DABAFIHH',
  command: :get_bank_certificate,
  customer_id: '<custid>',
  environment: 'production',
  pin: '<pin>',
}

client = Sepa::Client.new params
response = client.send_request

puts "#{response.response_code} #{response.response_text}"

File.write "danske.out", response.content
File.write "danskes_bank_encryption_certificate.crt", response.bank_encryption_certificate
File.write "danskes_bank_signing_certificate.crt", response.bank_signing_certificate
File.write "danskes_bank_root_certificate.crt", response.bank_root_certificate

But I only get:
./danske-getbankcert.rb
00 OK
/usr/local/lib/ruby/gems/2.3.0/gems/sepafm-1.1.9/lib/sepa/banks/danske/danske_response.rb:204:in `decrypt_embedded_key': undefined method `content' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/sepafm-1.1.9/lib/sepa/banks/danske/danske_response.rb:148:in `decrypt_application_response'
        from /usr/local/lib/ruby/gems/2.3.0/gems/sepafm-1.1.9/lib/sepa/banks/danske/danske_response.rb:13:in `application_response'
        from /usr/local/lib/ruby/gems/2.3.0/gems/sepafm-1.1.9/lib/sepa/response.rb:160:in `content'
        from ./danske-getbankcert.rb:20:in `<main>'

/usr/local/bin/ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [i686-linux]

Thanks in advance,
Toni

**Comment by tontsa** [comment]
Hi,

While investigating this more seems Danske Bank has changed the schema not to include bxd (http://model.bxd.fi) in the application response. Instead the NSes are:
`GetBankCertificateOut xmlns="http://danskebank.dk/PKI/PKIFactoryService"
pkie:GetBankCertificateResponse xmlns:pkie="http://danskebank.dk/PKI/PKIFactoryService/elements" xmlns="" xml:id="response"
`

**Comment by tontsa** [comment]
Hi,

Turns out ":get_bank_certificate" doesn't need to decrypt application response at all to acquire the bank public certs. So you can add to /sepa/banks/danske/danske_response.rb in decrypt_application_response method:
return unless encrypted_application_response.css('CipherValue', 'xmlns' => XMLENC)[1] before trying to decrypt anything. Also decrypt_embedded_key method needs return unless encrypted_application_response.css('CipherValue', 'xmlns' => XMLENC)[0]

Module works otherwise and this ticket can be closed
